/*
 * Minimal MCUXpresso USB device configuration for the NCR-2 recovery build.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef NCR2_USB_DEVICE_CONFIG_H
#define NCR2_USB_DEVICE_CONFIG_H

#define USB_DEVICE_CONFIG_KHCI 0U
#define USB_DEVICE_CONFIG_EHCI 1U
#define USB_DEVICE_CONFIG_LPCIP3511FS 0U
#define USB_DEVICE_CONFIG_LPCIP3511HS 0U
#define USB_DEVICE_CONFIG_DWC3 0U
#define USB_DEVICE_CONFIG_NUM 1U

#define USB_DEVICE_CONFIG_HID 1U
#define USB_DEVICE_CONFIG_CDC_ACM 0U
#define USB_DEVICE_CONFIG_MSC 0U
#define USB_DEVICE_CONFIG_MTP 0U
#define USB_DEVICE_CONFIG_AUDIO 0U
#define USB_DEVICE_CONFIG_PHDC 0U
#define USB_DEVICE_CONFIG_VIDEO 0U
#define USB_DEVICE_CONFIG_PRINTER 0U
#define USB_DEVICE_CONFIG_DFU 0U
#define USB_DEVICE_CONFIG_CCID 0U

#define USB_DEVICE_CONFIG_SELF_POWER 1U
#define USB_DEVICE_CONFIG_ENDPOINTS 4U
#define USB_DEVICE_CONFIG_USE_TASK 0U
#define USB_DEVICE_CONFIG_MAX_MESSAGES 8U
#define USB_DEVICE_CONFIG_USB20_TEST_MODE 0U
#define USB_DEVICE_CONFIG_CV_TEST 0U
#define USB_DEVICE_CONFIG_ROOT2_TEST 0U
#define USB_DEVICE_CONFIG_COMPLIANCE_TEST 0U
#define USB_DEVICE_CONFIG_EHCI_MAX_DTD 16U
#define USB_DEVICE_CONFIG_EHCI_ID_PIN_DETECT 0U
#define USB_DEVICE_CONFIG_BUFFER_PROPERTY_CACHEABLE 0U
#define USB_DEVICE_CONFIG_LOW_POWER_MODE 0U
#define USB_DEVICE_CONFIG_REMOTE_WAKEUP 0U
#define USB_DEVICE_CONFIG_LPM_L1 0U
#define USB_DEVICE_CONFIG_DETACH_ENABLE 0U
#define USB_DEVICE_CONFIG_ERROR_HANDLING 0U
#define USB_DEVICE_CONFIG_RETURN_VALUE_CHECK 0U
#define USB_DEVICE_CONFIG_SOF_NOTIFICATIONS 0U
#define USB_DEVICE_CONFIG_GET_SOF_COUNT 0U
#define USB_DEVICE_CONFIG_KEEP_ALIVE_MODE 0U
#define USB_DEVICE_CONFIG_CHARGER_DETECT 0U
#define USB_DEVICE_CONFIG_OTG 0U

#endif
