"""Generate the C sources the effect editor compiles and exports.

Two kinds of output live here:

1. a throwaway configuration unit that binds an editor session's registry
   and program to the real `effect_runtime`/`program_runtime` symbols the
   host harness links against; and
2. review-ready firmware sources — an effect header and a
   `programs_builtin.c`-style program block — so a previewed design can
   be moved into `firmware/app` without hand transcription.

Nothing here is device specific and nothing is written to the repository;
callers decide what to do with the returned text.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Iterable, Sequence


VENDOR_OPEN = 0x4F50454E

# Only non-static descriptors can join a generated registry.
DESCRIPTOR_PATTERN = re.compile(
    r"^[ \t]*const[ \t]+effect_descriptor_t[ \t]+"
    r"([A-Za-z_][A-Za-z0-9_]*)[ \t]*=",
    re.MULTILINE,
)
STATIC_DESCRIPTOR_PATTERN = re.compile(
    r"^[ \t]*static[ \t]+const[ \t]+effect_descriptor_t[ \t]+"
    r"([A-Za-z_][A-Za-z0-9_]*)[ \t]*=",
    re.MULTILINE,
)
IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

BUILTIN_DESCRIPTORS = (
    "ncr2_effect_basic_gain",
    "ncr2_effect_basic_soft_clip",
    "ncr2_effect_steel_acoustic",
    "ncr2_effect_nylon_classical",
    "ncr2_effect_twelve_string",
    "ncr2_effect_banjo",
    "ncr2_effect_sitar",
    "ncr2_effect_upright_bass",
    "ncr2_effect_bowed_cello",
    "ncr2_effect_clarinet",
)

# `effects_basic.h` predates any naming convention an editor could infer
# ("Basic Gain" is EFFECT_OPEN_BASIC_GAIN_ID but its parameter is
# EFFECT_GAIN_PARAMETER_GAIN), so exported C quotes the real macros for
# shipped effects and derives them only for effects authored in-session.
BUILTIN_EFFECT_MACROS: dict[tuple[int, int], dict[str, Any]] = {
    (VENDOR_OPEN, 1): {
        "header": "effects_basic.h",
        "id": "EFFECT_OPEN_BASIC_GAIN_ID",
        "parameters": {1: "EFFECT_GAIN_PARAMETER_GAIN"},
    },
    (VENDOR_OPEN, 2): {
        "header": "effects_basic.h",
        "id": "EFFECT_OPEN_BASIC_SOFT_CLIP_ID",
        "parameters": {
            1: "EFFECT_SOFT_CLIP_PARAMETER_DRIVE",
            2: "EFFECT_SOFT_CLIP_PARAMETER_LEVEL",
            3: "EFFECT_SOFT_CLIP_PARAMETER_MIX",
        },
    },
}

for _effect_id, _id_macro in (
    (0x100, "EFFECT_OPEN_STEEL_ACOUSTIC_ID"),
    (0x101, "EFFECT_OPEN_NYLON_CLASSICAL_ID"),
    (0x102, "EFFECT_OPEN_TWELVE_STRING_ID"),
    (0x103, "EFFECT_OPEN_BANJO_ID"),
    (0x104, "EFFECT_OPEN_SITAR_ID"),
    (0x105, "EFFECT_OPEN_UPRIGHT_BASS_ID"),
    (0x106, "EFFECT_OPEN_BOWED_CELLO_ID"),
    (0x107, "EFFECT_OPEN_CLARINET_ID"),
):
    BUILTIN_EFFECT_MACROS[(VENDOR_OPEN, _effect_id)] = {
        "header": "effects_instrument.h",
        "id": _id_macro,
        "parameters": {
            1: "EFFECT_INSTRUMENT_PARAMETER_TRANSFORMATION",
            2: "EFFECT_INSTRUMENT_PARAMETER_CHARACTER",
            3: "EFFECT_INSTRUMENT_PARAMETER_MIX",
            4: "EFFECT_INSTRUMENT_PARAMETER_SENSITIVITY",
        },
    }

GENERATED_BANNER = (
    "/* Generated by host/editor. Do not edit; regenerate instead. */"
)


class CodegenError(ValueError):
    """Raised when a session cannot be expressed as valid C."""


@dataclass(frozen=True)
class ProgramNode:
    vendor_id: int
    effect_id: int
    parameters: tuple[tuple[int, float], ...] = ()


@dataclass(frozen=True)
class ProgramSpec:
    name: str
    program_id: int
    nodes: tuple[ProgramNode, ...]
    vendor_id: int = VENDOR_OPEN
    bank_name: str = "Editor Bank"
    bank_id: int = 1


def format_float(value: float) -> str:
    """Render a finite float as a C `float` literal."""
    number = float(value)
    if number != number or number in (float("inf"), float("-inf")):
        raise CodegenError("parameter values must be finite")
    text = repr(number)
    if text.endswith(".0"):
        text = text[:-2] + ".0"
    elif "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return f"{text}F"


def format_u32(value: int) -> str:
    number = int(value)
    if number < 0 or number > 0xFFFFFFFF:
        raise CodegenError("identifiers must fit in uint32_t")
    return f"UINT32_C(0x{number:08X})"


def escape_c_string(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    if any(character < " " or character == "\x7f" for character in escaped):
        raise CodegenError("names must not contain control characters")
    return escaped


def slug(text: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_").lower()
    return cleaned or "unnamed"


def macro_name(*parts: str) -> str:
    return "_".join(slug(part).upper() for part in parts if part)


def sizeof_lines(table: str, indent: str) -> list[str]:
    """Wrap an array-count expression the way firmware sources do."""
    return [
        f"{indent}sizeof({table}) /",
        f"{indent}    sizeof({table}[0]),",
    ]


def validate_identifier(name: str) -> str:
    if IDENTIFIER_PATTERN.match(name) is None:
        raise CodegenError(f"invalid C identifier: {name!r}")
    return name


def parse_descriptor_symbols(source: str) -> list[str]:
    """Return externally visible effect descriptor symbols in a source."""
    return [
        match.group(1)
        for match in DESCRIPTOR_PATTERN.finditer(source)
    ]


def parse_static_descriptor_symbols(source: str) -> list[str]:
    return [
        match.group(1)
        for match in STATIC_DESCRIPTOR_PATTERN.finditer(source)
    ]


def generate_config(
    program: ProgramSpec,
    extra_descriptors: Sequence[str] = (),
    bake_parameters: bool = True,
) -> str:
    """Build the configuration unit linked into the host harness.

    With `bake_parameters` the program descriptor carries its parameter
    values, which is what `program_prepare` validates on the device. The
    editor also renders with `bake_parameters=False` and applies values
    through `effect_chain_set_parameter` instead, so moving a control
    does not invalidate the compiled binary.
    """
    symbols = list(BUILTIN_DESCRIPTORS)
    for symbol in extra_descriptors:
        validate_identifier(symbol)
        if symbol not in symbols:
            symbols.append(symbol)

    lines: list[str] = [
        GENERATED_BANNER,
        "",
        '#include "effect_runtime.h"',
        '#include "effects_basic.h"',
        '#include "effects_instrument.h"',
        '#include "program_runtime.h"',
        "",
    ]
    externals = [
        symbol
        for symbol in symbols
        if symbol not in BUILTIN_DESCRIPTORS
    ]
    for symbol in externals:
        lines.append(f"extern const effect_descriptor_t {symbol};")
    if externals:
        lines.append("")

    lines.append(
        "static const effect_descriptor_t *const editor_effect_table[] = {"
    )
    for symbol in symbols:
        lines.append(f"    &{symbol},")
    lines.extend(
        [
            "};",
            "",
            "const effect_registry_t editor_registry = {",
            "    editor_effect_table,",
            "    sizeof(editor_effect_table) /",
            "        sizeof(editor_effect_table[0]),",
            "};",
            "",
        ]
    )

    for index, node in enumerate(program.nodes):
        if not bake_parameters or not node.parameters:
            continue
        lines.append(
            "static const program_parameter_value_t "
            f"editor_node_{index}_parameters[] = {{"
        )
        for parameter_id, value in node.parameters:
            lines.append(
                f"    {{ {format_u32(parameter_id)}, "
                f"{format_float(value)} }},"
            )
        lines.extend(["};", ""])

    if program.nodes:
        lines.append(
            "static const program_node_descriptor_t editor_nodes[] = {"
        )
        for index, node in enumerate(program.nodes):
            table = f"editor_node_{index}_parameters"
            has_parameters = bake_parameters and bool(node.parameters)
            lines.extend(
                [
                    "    {",
                    "        {",
                    f"            {format_u32(node.vendor_id)},",
                    f"            {format_u32(node.effect_id)},",
                    "        },",
                    f"        {table if has_parameters else 'NULL'},",
                ]
            )
            if has_parameters:
                lines.extend(sizeof_lines(table, "        "))
            else:
                lines.append("        0U,")
            lines.append("    },")
        lines.extend(["};", ""])

    lines.extend(
        [
            "const program_descriptor_t editor_program = {",
            "    .key = {",
            f"        {format_u32(program.vendor_id)},",
            f"        {format_u32(program.program_id)},",
            "    },",
            f'    .name = "{escape_c_string(program.name)}",',
            "    .nodes = " + ("editor_nodes," if program.nodes else "NULL,"),
            "    .node_count = "
            + (
                "sizeof(editor_nodes) / sizeof(editor_nodes[0]),"
                if program.nodes
                else "0U,"
            ),
            "};",
            "",
            "static const program_descriptor_t *const "
            "editor_program_table[] = {",
            "    &editor_program,",
            "};",
            "",
            "const program_catalog_t editor_catalog = {",
            "    editor_program_table,",
            "    sizeof(editor_program_table) /",
            "        sizeof(editor_program_table[0]),",
            "};",
            "",
            "static const program_key_t editor_bank_programs[] = {",
            "    {",
            f"        {format_u32(program.vendor_id)},",
            f"        {format_u32(program.program_id)},",
            "    },",
            "};",
            "",
            "static const program_bank_descriptor_t editor_bank = {",
            "    .key = {",
            f"        {format_u32(program.vendor_id)},",
            f"        {format_u32(program.bank_id)},",
            "    },",
            f'    .name = "{escape_c_string(program.bank_name)}",',
            "    .programs = editor_bank_programs,",
            "    .program_count =",
            "        sizeof(editor_bank_programs) /",
            "            sizeof(editor_bank_programs[0]),",
            "};",
            "",
            "static const program_bank_descriptor_t *const "
            "editor_bank_table[] = {",
            "    &editor_bank,",
            "};",
            "",
            "const program_library_t editor_library = {",
            "    &editor_catalog,",
            "    editor_bank_table,",
            "    sizeof(editor_bank_table) /",
            "        sizeof(editor_bank_table[0]),",
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def generate_effect_header(
    effect: dict[str, Any],
    symbol: str,
    file_slug: str,
) -> str:
    """Emit the public header for an authored effect."""
    validate_identifier(symbol)
    guard = f"NCR2_EFFECTS_{macro_name(file_slug)}_H"
    effect_macro = macro_name("effect_open", effect["name"], "id")
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "effect_runtime.h"',
        "",
        f"#define {effect_macro} "
        f"{format_u32(int(effect['effect_id']))}",
        "",
    ]
    for parameter in effect.get("parameters", ()):
        lines.append(
            "#define "
            + macro_name("effect", effect["name"], "parameter", parameter["name"])
            + f" {format_u32(int(parameter['parameter_id']))}"
        )
    if effect.get("parameters"):
        lines.append("")
    lines.extend(
        [
            f"extern const effect_descriptor_t {symbol};",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def effect_id_reference(effect: dict[str, Any]) -> str:
    """Return the C expression naming an effect id."""
    key = (int(effect["vendor_id"]), int(effect["effect_id"]))
    builtin = BUILTIN_EFFECT_MACROS.get(key)
    if builtin is not None:
        return str(builtin["id"])
    if effect.get("authored"):
        return macro_name("effect_open", effect["name"], "id")
    return format_u32(key[1])


def parameter_reference(
    effect: dict[str, Any],
    parameter: dict[str, Any],
) -> str:
    """Return the C expression naming a parameter id."""
    key = (int(effect["vendor_id"]), int(effect["effect_id"]))
    parameter_id = int(parameter["parameter_id"])
    builtin = BUILTIN_EFFECT_MACROS.get(key)
    if builtin is not None:
        macro = builtin["parameters"].get(parameter_id)
        if macro is not None:
            return str(macro)
    if effect.get("authored"):
        return macro_name(
            "effect", effect["name"], "parameter", parameter["name"]
        )
    return format_u32(parameter_id)


def program_includes(effects: Iterable[dict[str, Any]]) -> list[str]:
    headers = ["program_runtime.h"]
    for effect in effects:
        key = (int(effect["vendor_id"]), int(effect["effect_id"]))
        builtin = BUILTIN_EFFECT_MACROS.get(key)
        if builtin is not None:
            header = str(builtin["header"])
        elif effect.get("authored"):
            header = f"effects_{slug(effect['name'])}.h"
        else:
            continue
        if header not in headers:
            headers.append(header)
    return headers


def generate_program_source(
    program: ProgramSpec,
    catalog: Iterable[dict[str, Any]],
) -> str:
    """Emit a `programs_builtin.c`-style block for a designed program."""
    effects = {
        (int(entry["vendor_id"]), int(entry["effect_id"])): entry
        for entry in catalog
    }
    used = []
    for index, node in enumerate(program.nodes):
        effect = effects.get((node.vendor_id, node.effect_id))
        if effect is None:
            raise CodegenError(
                f"program node {index} references an unknown effect"
            )
        used.append(effect)

    if not program.nodes:
        raise CodegenError(
            "an exported program needs at least one effect"
        )

    name = slug(program.name)
    program_macro = macro_name("program_open", program.name, "id")
    lines = [
        "/* Program designed with host/editor; review before merging. */",
        "",
    ]
    lines.extend(
        f'#include "{header}"' for header in program_includes(used)
    )
    lines.extend(
        [
            "",
            "/* Move this identity to programs_builtin.h when adopting "
            "the program. */",
            f"#define {program_macro} {format_u32(program.program_id)}",
            "",
        ]
    )

    node_tables: list[tuple[str, bool]] = []
    for index, node in enumerate(program.nodes):
        effect = used[index]
        table = f"{name}_node_{index}_parameters"
        node_tables.append((table, bool(node.parameters)))
        if not node.parameters:
            continue
        parameters = {
            int(entry["parameter_id"]): entry
            for entry in effect.get("parameters", ())
        }
        lines.append(
            f"static const program_parameter_value_t {table}[] = {{"
        )
        for parameter_id, value in node.parameters:
            schema = parameters.get(int(parameter_id))
            if schema is None:
                raise CodegenError(
                    f"unknown parameter {parameter_id} on node {index}"
                )
            lines.append(
                "    { "
                + parameter_reference(effect, schema)
                + f", {format_float(value)} }},"
            )
        lines.extend(["};", ""])

    lines.append(
        f"static const program_node_descriptor_t {name}_nodes[] = {{"
    )
    for index, node in enumerate(program.nodes):
        effect = used[index]
        table, has_parameters = node_tables[index]
        lines.extend(
            [
                "    {",
                "        {",
                "            EFFECT_VENDOR_OPEN,",
                f"            {effect_id_reference(effect)},",
                "        },",
                f"        {table if has_parameters else 'NULL'},",
            ]
        )
        if has_parameters:
            lines.extend(sizeof_lines(table, "        "))
        else:
            lines.append("        0U,")
        lines.append("    },")
    lines.extend(
        [
            "};",
            "",
            f"static const program_descriptor_t {name}_program = {{",
            "    .key = {",
            "        EFFECT_VENDOR_OPEN,",
            f"        {program_macro},",
            "    },",
            f'    .name = "{escape_c_string(program.name)}",',
            f"    .nodes = {name}_nodes,",
            "    .node_count =",
            f"        sizeof({name}_nodes) / sizeof({name}_nodes[0]),",
            "};",
            "",
        ]
    )
    return "\n".join(lines)


EFFECT_TEMPLATE = '''#include "effect_runtime.h"

/*
 * Authored in host/editor. The runtime forbids allocation, flash access,
 * logging, and locking inside these callbacks: all state lives in the
 * context the chain hands back on every call.
 */

#define EFFECT_OPEN_{MACRO}_ID UINT32_C({effect_id})

#define EFFECT_{MACRO}_PARAMETER_AMOUNT UINT32_C(1)
#define EFFECT_{MACRO}_PARAMETER_MIX UINT32_C(2)

typedef struct {ident}_context {{
    float amount;
    float mix;
    float previous;
}} {ident}_context_t;

static uint16_t {ident}_initialize(
    void *opaque,
    uint32_t sample_rate,
    uint32_t maximum_block_frames)
{{
    {ident}_context_t *context = ({ident}_context_t *)opaque;

    (void)sample_rate;
    (void)maximum_block_frames;
    context->amount = 0.5F;
    context->mix = 1.0F;
    context->previous = 0.0F;
    return EFFECT_RUNTIME_OK;
}}

static void {ident}_reset(void *opaque)
{{
    {ident}_context_t *context = ({ident}_context_t *)opaque;

    context->previous = 0.0F;
}}

static uint16_t {ident}_process(
    void *opaque,
    effect_audio_block_t *block)
{{
    {ident}_context_t *context = ({ident}_context_t *)opaque;

    for (uint8_t channel = UINT8_C(0);
         channel < block->channel_count;
         ++channel) {{
        for (uint32_t frame = UINT32_C(0);
             frame < block->frame_count;
             ++frame) {{
            float dry = block->channels[channel][frame];
            float smoothed =
                context->previous +
                context->amount * (dry - context->previous);
            float wet = smoothed;

            context->previous = smoothed;
            block->channels[channel][frame] =
                dry + (wet - dry) * context->mix;
        }}
    }}
    return EFFECT_RUNTIME_OK;
}}

static uint16_t {ident}_set_parameter(
    void *opaque,
    uint32_t parameter_id,
    float value)
{{
    {ident}_context_t *context = ({ident}_context_t *)opaque;

    if (parameter_id == EFFECT_{MACRO}_PARAMETER_AMOUNT) {{
        context->amount = value;
    }} else if (parameter_id == EFFECT_{MACRO}_PARAMETER_MIX) {{
        context->mix = value;
    }} else {{
        return EFFECT_RUNTIME_PARAMETER_NOT_FOUND;
    }}
    return EFFECT_RUNTIME_OK;
}}

static const effect_parameter_descriptor_t {ident}_parameters[] = {{
    {{
        EFFECT_{MACRO}_PARAMETER_AMOUNT,
        "Amount",
        "linear",
        0.001F,
        1.0F,
        0.5F,
    }},
    {{
        EFFECT_{MACRO}_PARAMETER_MIX,
        "Mix",
        "linear",
        0.0F,
        1.0F,
        1.0F,
    }},
}};

const effect_descriptor_t {symbol} = {{
    .key = {{
        EFFECT_VENDOR_OPEN,
        EFFECT_OPEN_{MACRO}_ID,
    }},
    .name = "{name}",
    .abi_version = EFFECT_RUNTIME_ABI_VERSION,
    .parameter_count =
        sizeof({ident}_parameters) /
            sizeof({ident}_parameters[0]),
    .parameters = {ident}_parameters,
    .context_size = sizeof({ident}_context_t),
    .context_alignment = _Alignof({ident}_context_t),
    .initialize = {ident}_initialize,
    .reset = {ident}_reset,
    .process = {ident}_process,
    .set_parameter = {ident}_set_parameter,
}};
'''


def effect_template(name: str, effect_id: int) -> str:
    """Return a compilable starting point for a new effect."""
    identifier = slug(name)
    return EFFECT_TEMPLATE.format(
        ident=identifier,
        MACRO=identifier.upper(),
        symbol=f"ncr2_effect_{identifier}",
        name=escape_c_string(name),
        effect_id=f"0x{int(effect_id):08X}",
    )
